# Generated by Django 3.0.5 on 2020-04-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Claim', to='hr.claimModel')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Department', to='hr.DepartmentModel')),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Employe', to='hr.EmployeModel')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Role', to='hr.RoleModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
