# Generated by Django 3.0.5 on 2020-04-10 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('manage_auth', '0002_auto_20200410_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='hr.RoleModel'),
        ),
    ]
