# Generated by Django 3.0.5 on 2020-04-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_auth', '0002_auto_20200423_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
