# Generated by Django 3.0.5 on 2020-04-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('manage_auth', '0003_auto_20200410_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='hr.DepartmentModel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='hr.EmployeModel'),
        ),
    ]
