# Generated by Django 3.0.5 on 2020-04-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('manage_auth', '0004_auto_20200410_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Claim', to='hr.claimModel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='hr.DepartmentModel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='hr.EmployeModel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='hr.RoleModel'),
        ),
    ]
