# Generated by Django 3.0.4 on 2020-04-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('accountId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('userName', models.CharField(blank=True, max_length=20)),
                ('password', models.DateField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('companyId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('companyName', models.CharField(max_length=30)),
                ('generalManger', models.CharField(max_length=30)),
                ('contactPerson', models.CharField(max_length=20)),
                ('workingField', models.CharField(max_length=20)),
                ('paymentOption', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('tinNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('departmentName', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeModel',
            fields=[
                ('employeId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=30, unique=True)),
                ('hiredDate', models.DateField(max_length=15)),
                ('telephone', models.CharField(max_length=15)),
                ('birthDate', models.DateField(max_length=15)),
                ('termOfEmployment', models.DateField(max_length=10)),
                ('role', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('invoiceNo', models.IntegerField()),
                ('ItemId', models.IntegerField()),
                ('subTotal', models.FloatField()),
                ('Total', models.FloatField()),
                ('Tax', models.FloatField()),
                ('retailPrice', models.IntegerField()),
                ('date', models.DateField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('orderName', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('orderDate', models.DateField(max_length=20)),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipmentId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('receivedStatus', models.CharField(max_length=30)),
                ('conditionOnTrack', models.CharField(max_length=30)),
                ('receivedBy', models.CharField(max_length=20)),
                ('dateOnTrack', models.DateField()),
                ('arrivalDate', models.DateField()),
                ('departureDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('shipmentId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('orderName', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='siv',
            fields=[
                ('sivId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sivDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('orderId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('orderName', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('itemName', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField()),
                ('catagory', models.CharField(max_length=10)),
                ('subCatagory', models.CharField(max_length=10)),
                ('retailPrice', models.FloatField()),
                ('packaging', models.CharField(max_length=20)),
                ('orderId', models.ManyToManyField(to='hr.Order')),
            ],
        ),
    ]
