# Generated by Django 3.0.5 on 2020-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sivmodel',
            name='itemId',
            field=models.IntegerField(),
        ),
    ]
