# Generated by Django 3.0.5 on 2020-05-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemmodel',
            unique_together=set(),
        ),
    ]
