# Generated by Django 3.0.5 on 2020-04-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employemodel',
            name='level',
            field=models.ForeignKey(db_column='levelId', default=6, on_delete=django.db.models.deletion.CASCADE, to='hr.claimModel', verbose_name='Claim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employemodel',
            name='roles',
            field=models.ForeignKey(db_column='roleId', default=8, on_delete=django.db.models.deletion.CASCADE, to='hr.RoleModel', verbose_name='Role'),
            preserve_default=False,
        ),
    ]
