# Generated by Django 3.0.5 on 2020-04-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sivmodel',
            old_name='approve',
            new_name='sivStatus',
        ),
        migrations.AddField(
            model_name='sivmodel',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.OrderModel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sivmodel',
            unique_together={('sivId', 'order')},
        ),
    ]
