# Generated by Django 3.0.4 on 2020-04-04 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('accountId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('userName', models.CharField(blank=True, max_length=20)),
                ('password', models.DateField(max_length=25)),
                ('role', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmployAddressModel',
            fields=[
                ('locationId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeModel',
            fields=[
                ('employeId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('hiredDate', models.DateField(max_length=15)),
                ('telephone', models.CharField(max_length=15)),
                ('birthDate', models.DateField(max_length=15)),
                ('termOfEmployment', models.DateField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.AddField(
            model_name='employaddressmodel',
            name='employe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeModel'),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='employe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeModel'),
        ),
    ]
