# Generated by Django 3.0.5 on 2020-04-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employemodel',
            name='has_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employemodel',
            name='termOfEmployment',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Hourly', 'Hourly')], max_length=20, verbose_name='Term of Employment'),
        ),
        migrations.AlterField(
            model_name='sivmodel',
            name='sivDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
