# Generated by Django 3.0.5 on 2020-04-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemModel',
            fields=[
                ('itemId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('warehouseName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('retailPrice', models.FloatField()),
                ('packaging', models.CharField(max_length=100)),
                ('discount', models.IntegerField(null=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.CatagoryModel', verbose_name='Catagory')),
            ],
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='hr.InventoryItemModel'),
            preserve_default=False,
        ),
    ]
