# Generated by Django 3.0.4 on 2020-04-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatagoryModel',
            fields=[
                ('subCatagory', models.CharField(auto_created=True, max_length=20)),
                ('catagory', models.CharField(auto_created=True, max_length=20)),
                ('catagoryId', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='claimModel',
            fields=[
                ('levelId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('level', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='companyModel',
            fields=[
                ('companyId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('companyName', models.CharField(max_length=30, verbose_name='Company name')),
                ('generalManger', models.CharField(max_length=30, verbose_name='General manager')),
                ('contactPerson', models.CharField(max_length=20, verbose_name='Contact person')),
                ('workingField', models.CharField(max_length=20, verbose_name='Working Field')),
                ('paymentOption', models.CharField(max_length=20, verbose_name='Payment option')),
                ('email', models.EmailField(max_length=30)),
                ('tinNumber', models.IntegerField(verbose_name='Tin number')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('invoiceId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('invoiceNo', models.IntegerField(verbose_name='Invoice number')),
                ('ItemId', models.IntegerField()),
                ('subTotal', models.FloatField(verbose_name='Sub total')),
                ('Total', models.FloatField()),
                ('Tax', models.FloatField()),
                ('retailPrice', models.IntegerField()),
                ('date', models.DateField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('itemId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('itemName', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField()),
                ('retailPrice', models.FloatField()),
                ('packaging', models.CharField(max_length=20)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.CatagoryModel', verbose_name='Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('orderId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('orderNumber', models.IntegerField(verbose_name='Order number')),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('orderDate', models.DateField(max_length=20)),
                ('discount', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.ItemModel', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('roleId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentModel',
            fields=[
                ('shipmentId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('receivedStatus', models.CharField(max_length=30, verbose_name='Recieved Status')),
                ('conditionOnTrack', models.CharField(max_length=30, verbose_name='Condition on truack')),
                ('receivedBy', models.CharField(max_length=20, verbose_name='Recieved By')),
                ('dateOnTrack', models.DateField(verbose_name='Date on truck')),
                ('arrivalDate', models.DateField(verbose_name='Arrival date')),
                ('departureDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentStatusModel',
            fields=[
                ('shipmentId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('orderName', models.CharField(max_length=20, verbose_name='Order name')),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sivModel',
            fields=[
                ('sivId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sivDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('orderId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('orderName', models.CharField(max_length=20, verbose_name='Order name')),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='item',
            name='orderId',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='ShipmentStatus',
        ),
        migrations.DeleteModel(
            name='siv',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='employemodel',
            name='department',
            field=models.ForeignKey(default=133, on_delete=django.db.models.deletion.CASCADE, to='hr.DepartmentModel', verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='userName',
            field=models.CharField(blank=True, max_length=20, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='departmentName',
            field=models.CharField(blank=True, max_length=20, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='employemodel',
            name='birthDate',
            field=models.DateField(max_length=15, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='employemodel',
            name='firstName',
            field=models.CharField(max_length=15, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='employemodel',
            name='hiredDate',
            field=models.DateField(max_length=15, verbose_name='Hired date'),
        ),
        migrations.AlterField(
            model_name='employemodel',
            name='lastName',
            field=models.CharField(max_length=15, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='employemodel',
            name='termOfEmployment',
            field=models.DateField(max_length=10, verbose_name='Term of Employment'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.DepartmentModel', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='claimmodel',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.RoleModel', verbose_name='Role'),
        ),
    ]
