# Generated by Django 3.0.5 on 2020-04-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employemodel',
            name='termOfEmployment',
            field=models.CharField(choices=[('Permament', 'Permament'), ('Temporary', 'Temporary'), ('Hourly', 'Hourly')], max_length=20, verbose_name='Term of Employment'),
        ),
    ]
