# Generated by Django 3.0.5 on 2020-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='orderNumber',
            field=models.IntegerField(unique=True, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='shipmentschedulemodel',
            name='shipmentNumber',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
