# Generated by Django 3.0.5 on 2020-04-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='orderid',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='orderNumber',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sivmodel',
            name='sivDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
