# Generated by Django 3.0.4 on 2020-04-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200404_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodel',
            name='quantity',
        ),
    ]
