# Generated by Django 3.0.5 on 2020-04-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200414_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employemodel',
            name='department',
            field=models.ForeignKey(db_column='departmentId', on_delete=django.db.models.deletion.CASCADE, to='hr.DepartmentModel', verbose_name='Department'),
        ),
    ]
