# Generated by Django 3.0.5 on 2020-04-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200421_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.OrderModel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invoicemodel',
            unique_together={('invoiceId', 'order')},
        ),
    ]
