# Generated by Django 3.0.5 on 2020-04-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200409_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagorymodel',
            name='catagory',
            field=models.CharField(auto_created=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='catagorymodel',
            name='subCatagory',
            field=models.CharField(auto_created=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='companyName',
            field=models.CharField(max_length=30, unique=True, verbose_name='Company name'),
        ),
    ]
