# Generated by Django 3.0.5 on 2020-04-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200417_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='date',
            field=models.DateField(auto_now=True, max_length=20),
        ),
    ]
