# Generated by Django 3.0.5 on 2020-04-24 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200423_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sivmodel',
            old_name='approve',
            new_name='sivStatus',
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='order',
            field=models.ForeignKey(default=1212, on_delete=django.db.models.deletion.CASCADE, to='hr.OrderModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sivmodel',
            name='order',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='hr.OrderModel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invoicemodel',
            unique_together={('invoiceId', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='sivmodel',
            unique_together={('sivId', 'order')},
        ),
    ]
