# Generated by Django 3.0.5 on 2020-04-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200428_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='orderName',
        ),
    ]
