# Generated by Django 3.0.5 on 2020-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200410_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='sivmodel',
            name='approve',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='paymentOption',
            field=models.CharField(choices=[('VAT', 'VAT'), ('TOT', 'TOT')], max_length=100),
        ),
    ]
