# Generated by Django 3.0.4 on 2020-04-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200404_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employemodel',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employemodel',
            name='termOfEmployment',
            field=models.CharField(max_length=20),
        ),
    ]
