# Generated by Django 3.0.5 on 2020-05-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20200503_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.CompanyModel'),
            preserve_default=False,
        ),
    ]
