# Generated by Django 3.0.5 on 2020-04-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20200414_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='role',
            field=models.ForeignKey(db_column='roleId', default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.RoleModel', verbose_name='Role'),
            preserve_default=False,
        ),
    ]
