# Generated by Django 3.0.5 on 2020-04-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20200421_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='orderNumber',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Issued', 'Issued'), ('Delivery Scheduled', 'Delivery Scheduled'), ('Delivered', 'Delivered'), ('Invoiced', 'Invoiced')], default='', max_length=100),
        ),
    ]
