# Generated by Django 3.0.5 on 2020-04-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20200417_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitemmodel',
            name='itemName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
