# Generated by Django 3.0.5 on 2020-04-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20200409_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
