# Generated by Django 3.0.5 on 2020-04-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20200417_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitemmodel',
            name='ItemId',
        ),
    ]
