# Generated by Django 3.0.5 on 2020-04-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20200409_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employemodel',
            name='level',
        ),
        migrations.RemoveField(
            model_name='employemodel',
            name='role',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='ItemId',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='invoiceNo',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='retailPrice',
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='salesPerson',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sivmodel',
            name='itemId',
            field=models.IntegerField(default=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sivmodel',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sivmodel',
            name='warehouseName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='itemName',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceLineItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('unitPrice', models.FloatField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('ItemId', models.IntegerField()),
                ('item_discount', models.FloatField(max_length=100)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.InvoiceModel')),
            ],
        ),
    ]
