# Generated by Django 3.0.5 on 2020-04-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20200425_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitemmodel',
            name='amount',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
