# Generated by Django 3.0.5 on 2020-04-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_departmentmodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='department',
            field=models.ForeignKey(db_column='levelId', on_delete=django.db.models.deletion.CASCADE, to='hr.claimModel', verbose_name='Level'),
        ),
    ]
