# Generated by Django 3.0.5 on 2020-04-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_invoicelineitemmodel_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitemmodel',
            name='amount',
        ),
    ]
