# Generated by Django 3.0.5 on 2020-04-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_invoicelineitemmodel_itemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitemmodel',
            name='item_discount',
        ),
    ]
