# Generated by Django 3.0.5 on 2020-04-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20200414_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolemodel',
            old_name='department',
            new_name='Level',
        ),
    ]
