# Generated by Django 3.0.5 on 2020-04-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20200409_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='orderNumber',
            field=models.IntegerField(verbose_name='Order number'),
        ),
    ]
