# Generated by Django 3.0.5 on 2020-04-14 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20200414_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.RoleModel', verbose_name='Role'),
        ),
    ]
