# Generated by Django 3.0.5 on 2020-04-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20200409_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='orderQuantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
