# Generated by Django 3.0.5 on 2020-04-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_remove_invoicelineitemmodel_item_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitemmodel',
            name='itemName',
            field=models.CharField(max_length=100),
        ),
    ]
