# Generated by Django 3.0.5 on 2020-04-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_auto_20200414_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='role',
        ),
    ]
