# Generated by Django 3.0.5 on 2020-04-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_auto_20200417_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sivitemlistmodel',
            name='itemId',
        ),
    ]
