# Generated by Django 3.0.5 on 2020-04-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_ordermodel_orderquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employemodel',
            name='termOfEmployment',
            field=models.CharField(max_length=10, verbose_name='Term of Employment'),
        ),
    ]
