# Generated by Django 3.0.5 on 2020-04-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_auto_20200410_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='warehouseName',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catagorymodel',
            name='catagory',
            field=models.CharField(auto_created=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='catagorymodel',
            name='subCatagory',
            field=models.CharField(auto_created=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='companyName',
            field=models.CharField(max_length=100, unique=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='contactPerson',
            field=models.CharField(max_length=100, verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='generalManger',
            field=models.CharField(max_length=100, verbose_name='General manager'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='paymentOption',
            field=models.CharField(max_length=100, verbose_name='Payment option'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='workingField',
            field=models.CharField(max_length=100, verbose_name='Working Field'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='itemName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='packaging',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipmentschedulemodel',
            name='conditionOnTrack',
            field=models.CharField(max_length=100, verbose_name='Condition on truack'),
        ),
        migrations.AlterField(
            model_name='shipmentschedulemodel',
            name='receivedBy',
            field=models.CharField(max_length=100, verbose_name='Recieved By'),
        ),
        migrations.AlterField(
            model_name='shipmentschedulemodel',
            name='receivedStatus',
            field=models.CharField(max_length=100, verbose_name='Recieved Status'),
        ),
    ]
