# Generated by Django 3.0.5 on 2020-04-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_remove_departmentmodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employemodel',
            name='roles',
            field=models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.CASCADE, related_name='xxx', to='hr.RoleModel', verbose_name='Role'),
        ),
    ]
