# Generated by Django 3.0.5 on 2020-04-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_auto_20200414_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employemodel',
            name='department',
            field=models.ForeignKey(db_column='departmentId', on_delete=django.db.models.deletion.CASCADE, related_name='department_detail', to='hr.DepartmentModel', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employemodel',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_detail', to='hr.RoleModel', verbose_name='Role'),
        ),
    ]
