# Generated by Django 3.0.5 on 2020-04-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_auto_20200414_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemodel',
            name='Level',
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='role_detail', to='hr.DepartmentModel', verbose_name='Department'),
            preserve_default=False,
        ),
    ]
