# Generated by Django 3.0.5 on 2020-04-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_auto_20200414_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimmodel',
            name='role',
            field=models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.CASCADE, related_name='claim_roles', to='hr.RoleModel', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_roles', to='hr.DepartmentModel', verbose_name='Department'),
        ),
    ]
