# Generated by Django 3.0.5 on 2020-04-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_auto_20200414_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimmodel',
            name='role',
            field=models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.CASCADE, related_name='role_levels', to='hr.RoleModel', verbose_name='Role'),
        ),
    ]
