from django.urls import path, include
from .views import (
    EmployeRUD,
    DepartmentRUD,
    RoleRUD,
    LevelRUD,
    OrderRUD,
    CatagoryRUD,
    ItemRUD,
    CompanyRUD,
    CompanyListAdd,
    EmployeListAdd,
    DepartmentListAdd,
    RoleListAdd,
    LevelListAdd,
    ItemListAdd,
    CatagoryListAdd,
    OrderListAdd,
    StatusListAdd,
    StatusRUD,
    ShipmentScheduleListAdd,
    ShipmentScheduleRUD,
    SivListAdd,
    SIVRUD,
    OrderItemRUD,
    OrderItemListAdd,
    InvoiceListAdd,
    InvoiceRUD,
)
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Erp System API",
        default_version="v1",
        description="Integrated Erp System that manage main business processes.",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@iwork.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    #    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path(
        "api/v1/docs/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "api/v1/doc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    path("api/v1/employe/<int:employeId>/", EmployeRUD.as_view()),
    path("api/v1/employe/", EmployeListAdd.as_view()),
    path("api/v1/generatesiv/<int:order>/", SIVRUD.as_view()),
    path("api/v1/generatesiv/", SivListAdd.as_view()),
    path("api/v1/schedulestatus/<int:shipmentId>/", ShipmentScheduleRUD.as_view()),
    path("api/v1/schedulestatus/", ShipmentScheduleListAdd.as_view()),
    path("api/v1/status/<int:order>/", StatusRUD.as_view()),
    path("api/v1/status/", StatusListAdd.as_view()),
    path("api/v1/department/<int:departmentId>/", DepartmentRUD.as_view()),
    path("api/v1/department/", DepartmentListAdd.as_view()),
    path("api/v1/role/<int:roleId>/", RoleRUD.as_view()),
    path("api/v1/role/", RoleListAdd.as_view()),
    path("api/v1/level/<int:levelId>/", LevelRUD.as_view()),
    path("api/v1/level/", LevelListAdd.as_view()),
    path("api/v1/item/<int:InventoryItemId>/", ItemRUD.as_view()),
    path("api/v1/item/", ItemListAdd.as_view()),
    path("api/v1/orderitem/<int:itemId>/", OrderItemRUD.as_view()),
    path("api/v1/orderitem/", OrderItemListAdd.as_view()),
    path("api/v1/catagory/<int:catagoryId>/", CatagoryRUD.as_view()),
    path("api/v1/catagory/", CatagoryListAdd.as_view()),
    path("api/v1/order/<int:orderNumber>/", OrderRUD.as_view()),
    path("api/v1/order/", OrderListAdd.as_view()),
    path("api/v1/company/<int:companyId>/", CompanyRUD.as_view()),
    path("api/v1/company/", CompanyListAdd.as_view()),
    path("api/v1/generateinvoice/<int:order>/", InvoiceRUD.as_view()),
    path("api/v1/generateinvoice/", InvoiceListAdd.as_view()),
]
